version: '2'
volumes: 
  mantis-db:
services:
  mantis:
    build:
      context: ./
    environment:
      MANTIS_ENABLE_ADMIN: 1
      MANTIS_CONFIG: |
        $$g_hostname = 'db';
        $$g_db_type = 'mysqli';
        $$g_database_name = 'mantis';
        $$g_db_username = 'root';
        $$g_db_password = 'mantis';
        $$g_crypto_master_salt='s+MIBUM6GgKXGeN7h5MPkb2GNW52CLObSQOvYZxVHjfmGYzKCcBLlGduJi/6aeCgRo5zCTT5XhEP2OdyVAXC9w==';
        $$g_log_level = LOG_EMAIL | LOG_EMAIL_RECIPIENT;
        $$g_log_destination = '';
        $$g_show_detailed_errors = ON;
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    volumes:
    - mantis-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mantis
      MYSQL_DATABASE: mantis
