#!/bin/bash
set -eo pipefail

echo '<?php ' > /var/www/html/config/config_inc.php
echo -e $MANTIS_CONFIG >> /var/www/html/config/config_inc.php
echo -e "\n?>" >> /var/www/html/config/config_inc.php

php scripts/send_emails.php
